version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows-dockerized
    environment:
      VERSION: "win11"
      RAM_SIZE: "10G"
      CPU_CORES: "6"
      DISK_SIZE: "128G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
